# If not running interactively, don't do anything
[[ $- != *i* ]] && return
DOTFILES="${HOME}/.dotfiles"
BASHRCD="${DOTFILES}/bashrc.d"
BASHRC="${HOME}/.bashrc"
#BASH_IT_THEME_SUPPORT="yes"

# The directories you would like to parse
DIRS=( "private" "completions" "aliases" )

# Load a local bashrc
function bashrc_local() {
  if [ -f "${DOTFILES}/bashrc.$1" ]; then
    source "${DOTFILES}/bashrc.$1"
  fi
}

function dot_get_files() {
  # $1: directory: ~/.dotfiles/bashrc.d/
  # $2: depth: 4 levels
  if [ -d "${BASHRCD}/$1" ]; then
    find ${BASHRCD}/$1 -maxdepth ${2:-4} -type f | grep -E "(.bash|.sh)$" | sort
  fi
}

# Source a local bashrc before everything
bashrc_local before

# Source every file on the bashrc.d directory
for f in $( dot_get_files . 1 ); do
  source $f
done

# Source every other file that is on the directories belonging to the array
for directory in ${DIRS[@]}; do
  for f in $( dot_get_files ${directory} ); do
    source $f
  done
done

# Use bash-it themes if support is enabled
if [[ $BASH_IT_THEME_SUPPORT ]]; then
  source bash-it-theme-support.bash
fi

# Load a bashrc after everything
bashrc_local after
