# If not running interactively, don't do anything
[[ $- != *i* ]] && return
DOTFILES="${HOME}/.dotfiles"
BASHRCD="${DOTFILES}/bashrc.d"
BASHRC="${HOME}/.bashrc"

# The directories you would like to parse
DIRS=( "private" "completions" "aliases" )

function dot_get_files() {
  # $1: directory: ~/.dotfiles/bashrc.d/
  # $2: depth: 4 levels
  if [ -d "${BASHRCD}/$1" ]; then
    find ${BASHRCD}/$1 -maxdepth ${2:-4} -type f | grep -E "(.bash|.sh)$" | sort
  fi
}

# Source every file on the bashrc.d directory
for f in $( dot_get_files . 1 ); do
  source $f
done

# Source every other file that is on the directories belonging to the array
for directory in ${DIRS[@]}; do
  for f in $( dot_get_files ${directory} ); do
    source $f
  done
done
